version: "2"
services:
  rabbitmq:
    build: .docker/rabbitmq
    hostname: recia-notification-poc-1
    ports:
      - 15671:15671
      - 15672:15672
      - 15674:15674
      - 25672:25672
      - 4369:4369
      - 5671:5671
      - 5672:5672
    volumes:
      - "rabbitmq:/var/lib/rabbitmq"
      - "rabbitmq-plugins:/usr/lib/rabbitmq/lib/rabbitmq_server-3.6.14/plugins"
      - "rabbitmq-configuration:/etc/rabbitmq"
  node:
    build:
      context: .docker/node
      args:
        - GROUP_ID=${GROUP_ID}
        - USER_ID=${USER_ID}
        - GROUP_NAME=${GROUP_NAME}
        - USER_NAME=${USER_NAME}
    environment:
      - GROUP_ID=${GROUP_ID}
      - USER_ID=${USER_ID}
      - GROUP_NAME=${GROUP_NAME}
      - USER_NAME=${USER_NAME}
    working_dir: /app
    volumes:
      - .:/home/node/app
      - node-cache:/.cache
volumes:
  rabbitmq: ~
  rabbitmq-plugins: ~
  rabbitmq-configuration: ~
  node-cache: ~