logging:
  file:
    path: logs

spring:
  cache:
    type: caffeine
    cache-names: ldapUidByMail, ldapGroupMembers
    caffeine:
      spec: maximumSize=10000,expireAfterWrite=24h
  application:
    name: expanded-kafka-poc
  kafka:
    bootstrap-servers: localhost:29092,localhost:39092,localhost:49092
    consumer:
      group-id: expanded-consumer
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.value.default.type: fr.recia.model_kafka.model.ServiceEvent
        spring.json.trusted.packages: "*"
        security.protocol: SASL_PLAINTEXT
        sasl.mechanism: PLAIN
        sasl.jaas.config: >
          org.apache.kafka.common.security.plain.PlainLoginModule required
          username="expanded-consumer"
          password="G5DakRQxs3coJuG5";
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.trusted.packages: "*"
        security.protocol: SASL_PLAINTEXT
        sasl.mechanism: PLAIN
        sasl.jaas.config: >
          org.apache.kafka.common.security.plain.PlainLoginModule required
          username="expanded-consumer"
          password="G5DakRQxs3coJuG5";
  ldap:
    urls: ldap://localhost:389
    base: dc=esco-centre,dc=fr
    username: cn=admin,ou=administrateurs,dc=esco-centre,dc=fr
    password: admin

ldap-group:
  branch-base: ou=groups
  retrieved-attribute: hasMember
  filter: "(&(objectClass=groupOfNames)(cn={0}))"

ldap-mail:
  branch-base: ou=people
  retrieved-attribute: uid
  filter: "(mail={0})"
