proxy:
  port: 1026

routing:
  rules:
    - header: From
      regex: ".*Nextcloud.*"
      processor: NextcloudProcessor
      service: "NEXTCLOUD"
      api-key: "Xif0duNVWzCPvzkk9LIcAZvpdYukD6ws"

notification-api:
  url: "http://localhost:8179/event/emit"

spring:
  application:
    smtp-proxy
  mail:
    host: localhost
    port: 1025
    #username: proxy
    #password: secure
    #properties:
      #mail:
        #smtp:
          #auth: true
          #starttls:
            #enable: true

