proxy:
  port: 1026

routing:
  rules:
    - header: From
      regex: ".*Nextcloud.*"
      processor: NextcloudProcessor
      service-name: "NEXTCLOUD"
      api-key: "Xif0duNVWzCPvzkk9LIcAZvpdYukD6ws"

notification-api:
  url: "http://localhost:8179/event/emit"

spring:
  application:
    smtp-proxy

  ldap:
    urls: ldap://localhost:389
    base: dc=esco-centre,dc=fr
    username: cn=admin,ou=administrateurs,dc=esco-centre,dc=fr
    password: admin

request:
  branch-base: ou=people
  retrieved-attribute: uid
  filter: "(mail={0})"